### PR TITLE
allow std::istream as pgn source

### PR DESCRIPTION
**Pull request by robertnurnberg**
No functional change, as `std::ifstream` is derived from `std::istream`.

### CODE REVIEW

**Comment by Disservin** [comment]
can you also change the documentation in `pgn-utilities.md` ? I might have to think of a way to auto generate the docs mh...

**Comment by Disservin** [comment]
Btw do you have a clue why my ci didnt run for this?

**Comment by robertnurnberg** [comment]
Done. I thought we might need the more general `istream` for the .gz decompression in the wdl repo. We will see if we do actually need it there in the end. But good to have it more general in your lib, right?

**Comment by Disservin** [comment]
> Done. I thought we might need the more general `istream` for the .gz decompression in the wdl repo. We will see if we do actually need it there in the end. But good to have it more general in your lib, right?

Yeah ;)

**Pull request merged**
